### ISSUE TITLE
Duplicate Items in Queue

### ISSUE THREAD

**Issue by digitalcoyote** [AlexanderSharykin/CardIdleRemastered#4] opened 2017-09-14 14:01 UTC
Not sure how it happened and I've been too busy to investigate as of yet, but I have multiples of the same games displayed in my queue. Working without issue and removes all copies of a game when it no longer has cards.

If there is anything I can provide to assist in investigating this, I will. Eventually I plan to debug and find out what is going on.

**Comment by AlexanderSharykin** [comment] 2017-09-14 18:49
hello
thank you for report, I will look into this
it will help a lot if you can provide a stable repro - a list of steps to repeat an issue (e.g. 1. click one thing 2. click another thing). I will be able to debug from there

**Comment by digitalcoyote** [comment] 2017-09-14 19:22
It's like that every time I load at the moment. I may need to clear queue and try to reproduce it

**Comment by AlexanderSharykin** [comment] 2017-09-16 17:20
@digitalcoyote 
Card Idle stores its data in xml file

C:\Users\%user_name%\AppData\Local\CardIdleRemastered\Settings.xml

Idle queue games ids are stored in `<IdleQueue></IdleQueue>` node, e.g. `<IdleQueue>1,2,3</IdleQueue>`

I think for some reasons one Id was written multiple times and Queue displayed one game more than once. I haven't found how it happened. Should be fixed in https://github.com/AlexanderSharykin/CardIdleRemastered/commit/dfd273021b9fe909fed361172a8e2b8c404153e4. Updated .exe is in Install folder. I will make a new release when you confirm that the issue is resolved

**Comment by digitalcoyote** [comment] 2017-09-18 02:32
If I magic up some incorrect data will that be enough to confirm?

**Comment by AlexanderSharykin** [comment] 2017-09-18 19:19
I meant that
> It's like that every time I load at the moment.
should not happen anymore :)
after fix Card Idle can ignore duplicated items like `<IdleQueue>209170,209170</IdleQueue>`
I am more interested how they got there in the first place

**Comment by digitalcoyote** [comment] 2017-09-18 19:21
It's certainly removing duplicates now. I am curious myself how they got there but beyond manually editing that file I have been unable to reproduce this with the pre-fix version.

**Closed** 2017-10-26 13:59 UTC
